#!/usr/bin/env python

import sys

print "const char* %s[] = {" % sys.argv[1]
with open(sys.argv[2]) as f:
    for line in f.readlines():
        print '  "%s",' % line.strip()
print "  0"
print "};"
